# Stage 1: download and extract binaries
FROM rockylinux:9 AS builder

ARG HADOOP_VERSION=3.3.6
ARG HBASE_VERSION=2.5.15
ARG ZK_VERSION=3.8.6
ARG SPARK_VERSION=3.5.8

RUN dnf install -y --allowerasing curl && rm -rf /var/cache/dnf

RUN curl -fsSL https://dlcdn.apache.org/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz \
    | tar xz -C /opt && mv /opt/hadoop-$HADOOP_VERSION /opt/hadoop

RUN curl -fsSL https://dlcdn.apache.org/hbase/$HBASE_VERSION/hbase-$HBASE_VERSION-hadoop3-bin.tar.gz \
    | tar xz -C /opt && mv /opt/hbase-$HBASE_VERSION-hadoop3 /opt/hbase

RUN curl -fsSL https://dlcdn.apache.org/zookeeper/zookeeper-$ZK_VERSION/apache-zookeeper-$ZK_VERSION-bin.tar.gz \
    | tar xz -C /opt && mv /opt/apache-zookeeper-$ZK_VERSION-bin /opt/zookeeper

RUN curl -fsSL https://dlcdn.apache.org/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop3-scala2.13.tgz \
    | tar xz -C /opt && mv /opt/spark-$SPARK_VERSION-bin-hadoop3-scala2.13 /opt/spark

RUN rm -rf \
    /opt/hadoop/share/doc \
    /opt/hbase/docs \
    /opt/zookeeper/docs \
    /opt/spark/examples \
    /opt/spark/data \
  && find /opt \( -name "*.bat" -o -name "*.cmd" -o -name "*.ps1" -o -name "*.a" \) -delete

# Stage 2: runtime image
FROM rockylinux:9

LABEL description="Hadoop 3.3.6 + HBase 2.5.15 + ZooKeeper 3.8.6 + Spark 3.5.8 - Learning Cluster"
LABEL maintainer="Hadoop Docker Learning"

ENV JAVA_HOME=/usr/lib/jvm/jre-11-openjdk
ENV HADOOP_HOME=/opt/hadoop
ENV HBASE_HOME=/opt/hbase
ENV ZK_HOME=/opt/zookeeper
ENV SPARK_HOME=/opt/spark
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
ENV HBASE_CONF_DIR=$HBASE_HOME/conf
ENV PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$HBASE_HOME/bin:$ZK_HOME/bin:$SPARK_HOME/bin

RUN dnf install -y --allowerasing \
        java-11-openjdk-headless java-11-openjdk-devel \
        openssh-server openssh-clients \
        nmap-ncat nano \
        which \
    && dnf install -y epel-release \
    && dnf install -y python3.11 python3.11-pip \
    && ln -sf /usr/bin/python3.11 /usr/bin/python3 \
    && ln -sf /usr/bin/pip3.11 /usr/bin/pip3 \
    && dnf clean all && rm -rf /var/cache/dnf

RUN python3 -m pip install --no-cache-dir \
        pandas matplotlib happybase thriftpy2

RUN ssh-keygen -t rsa -P '' -f /root/.ssh/id_rsa && \
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys && \
    chmod 600 /root/.ssh/authorized_keys && \
    ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' 2>/dev/null && \
    ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' 2>/dev/null && \
    sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
    echo "UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config

COPY --from=builder /opt/hadoop $HADOOP_HOME
COPY --from=builder /opt/hbase $HBASE_HOME
COPY --from=builder /opt/zookeeper $ZK_HOME
COPY --from=builder /opt/spark $SPARK_HOME

RUN mkdir -p /data/hdfs/namenode /data/hdfs/datanode /data/zookeeper /opt/scripts

COPY config/core-site.xml $HADOOP_CONF_DIR/core-site.xml
COPY config/hdfs-site.xml $HADOOP_CONF_DIR/hdfs-site.xml
COPY config/mapred-site.xml $HADOOP_CONF_DIR/mapred-site.xml
COPY config/yarn-site.xml $HADOOP_CONF_DIR/yarn-site.xml
COPY config/hbase-site.xml $HBASE_CONF_DIR/hbase-site.xml
COPY config/zoo.cfg $ZK_HOME/conf/zoo.cfg
COPY config/spark-defaults.conf $SPARK_HOME/conf/spark-defaults.conf
COPY scripts/regionservers $HBASE_CONF_DIR/regionservers
COPY scripts/bootstrap.sh /opt/scripts/bootstrap.sh

RUN echo "export JAVA_HOME=$JAVA_HOME" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
    echo "export HADOOP_HOME=$HADOOP_HOME" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
    echo "export HADOOP_CONF_DIR=$HADOOP_CONF_DIR" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
    echo "export HADOOP_HEAPSIZE=512" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
    echo "export HDFS_NAMENODE_OPTS=\"-Xms512m -Xmx512m\"" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
    echo "export HDFS_DATANODE_OPTS=\"-Xms256m -Xmx256m\"" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
    echo "export YARN_RESOURCEMANAGER_OPTS=\"-Xms512m -Xmx512m\"" >> $HADOOP_CONF_DIR/yarn-env.sh && \
    echo "export YARN_NODEMANAGER_OPTS=\"-Xms256m -Xmx256m\"" >> $HADOOP_CONF_DIR/yarn-env.sh && \
    echo "export YARN_HEAPSIZE=512" >> $HADOOP_CONF_DIR/yarn-env.sh && \
    echo "export HBASE_HEAPSIZE=512" >> $HBASE_CONF_DIR/hbase-env.sh && \
    echo "export HBASE_MASTER_OPTS=\"-Xms512m -Xmx512m\"" >> $HBASE_CONF_DIR/hbase-env.sh && \
    echo "export HBASE_REGIONSERVER_OPTS=\"-Xms512m -Xmx512m\"" >> $HBASE_CONF_DIR/hbase-env.sh && \
    echo "export HBASE_THRIFT_OPTS=\"-Xms256m -Xmx256m\"" >> $HBASE_CONF_DIR/hbase-env.sh && \
    chmod +x /opt/scripts/bootstrap.sh

RUN echo "alias clear='printf \"\\033c\"'" >> /etc/bashrc

RUN mkdir -p /var/run/sshd

EXPOSE 9870 8088 8042 16010 2181 9000 9090 9091

ENTRYPOINT ["/opt/scripts/bootstrap.sh"]
