spark.master                     yarn
spark.yarn.am.memory             512m
spark.executor.memory            512m
spark.executor.cores             1
spark.driver.memory              512m
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://hadoop-master:9000/spark-logs
spark.history.provider           org.apache.spark.deploy.history.FsHistoryProvider
spark.history.fs.logDirectory    hdfs://hadoop-master:9000/spark-logs
spark.sql.adaptive.enabled       true
spark.sql.adaptive.coalescePartitions.enabled true
spark.serializer                 org.apache.spark.serializer.KryoSerializer
